# Generated by Django 4.2.7 on 2023-11-05 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HydroponicGrower",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("x_size", models.PositiveIntegerField()),
                ("y_size", models.PositiveIntegerField()),
                (
                    "orientation",
                    models.CharField(choices=[("vertical", "Vertical"), ("horizontal", "Horizontal")], max_length=10),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="SeedTray",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("x_size", models.PositiveIntegerField()),
                ("y_size", models.PositiveIntegerField()),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="PlantInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("notes", models.TextField()),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("n_seeds_used", models.PositiveIntegerField()),
                (
                    "current_stage",
                    models.CharField(
                        choices=[("germination", "Germination"), ("growing", "Growing"), ("cropped", "Cropped")],
                        max_length=50,
                    ),
                ),
                ("datetime_stage_updated", models.DateTimeField(auto_now=True)),
                ("position_x", models.PositiveIntegerField(blank=True, null=True)),
                ("position_y", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "hydroponic_grower",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plants",
                        to="plants.hydroponicgrower",
                    ),
                ),
                (
                    "plant_info",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="plants.plantinfo"),
                ),
                (
                    "seed_tray",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plants",
                        to="plants.seedtray",
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="plant",
            constraint=models.UniqueConstraint(
                fields=("seed_tray", "position_x", "position_y"), name="unique_position_in_seedtray"
            ),
        ),
        migrations.AddConstraint(
            model_name="plant",
            constraint=models.UniqueConstraint(
                fields=("hydroponic_grower", "position_x", "position_y"), name="unique_position_in_hydroponicgrower"
            ),
        ),
    ]
