# Generated by Django 4.2.7 on 2023-11-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0003_alter_plant_plant_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
